language: python
python: 2.7
env:
  - TOXENV=py27
  - TOXENV=pypy
  - TOXENV=docs
install:
  - pip install tox
  # Unabashedly (and unsurprisingly) mostly stolen from here:
  # <https://github.com/alex/rply/blob/master/.travis.yml>
  - wget https://bitbucket.org/pypy/pypy/downloads/pypy-2.0.2-src.tar.bz2 --output-document - | tar --extract --bzip2 --directory=..
script:
  - PYTHONPATH="$PYTHONPATH:../pypy-2.0.2-src" tox
